### ISSUE TITLE
verify plugin exit status

### ISSUE THREAD

**Issue by watchmanpluginteam** [bryanheinz/watchman_check_mdm#1]
Hey Bryan!

In looking at the values here:

https://github.com/bryanheinz/watchman_check_mdm/blob/836b4e0ebb43fd04eb5f496a58bff9cc7fa41b8c/_check_mdm.plugin#L21-L24

We see that the exit codes don't line up with how our infrastructure behaves.

Would you let us know if these were copied from anything published by Watchman Monitoring?

**Comment by bryanheinz** [comment]
They weren't copied from any Watchman documentation. When I wrote the preferences part of the plugin I set "None" as a string. But, when I change the preference in Watchman's System Preference pane to, say, "Warn" instead of it setting the preference as a String "Warn" it sets the preference as an Integer, `1`.

When my plugin is reading the preference file and `mdm_warning` is set to "Warn" it reads Integer `1`. The code that follows the comment you mentioned (`# 0 == None, Notify`) actually converts the preference integer into Watchman's exit status codes.
https://github.com/bryanheinz/watchman_check_mdm/blob/836b4e0ebb43fd04eb5f496a58bff9cc7fa41b8c/_check_mdm.plugin#L25-L40

The plugin maps the read preference Integers to 0==20, 1==200, 2==2. Reading the `mdm_warning` preference set to `"Warn"` gets read as `1` from the preferences, then converted to `mdm_warn_level = 200`.

The comment listed above was a note to myself on how to map Watchman's preference integer to the exit code I wanted the plugin to use.

Does that answer your question?
